module.exports = {
    CREATE_ROOM_FROM_CLIENT: 'CREATE_ROOM_FROM_CLIENT',
    CREATE_ROOM_FROM_SERVER: 'CREATE_ROOM_FROM_SERVER',
    JOIN_ROOM_FROM_CLIENT: 'JOIN_ROOM_FROM_CLIENT',
    JOIN_ROOM_FROM_SERVER: 'JOIN_ROOM_FROM_SERVER',
    SEND_PLAYER_TIME_FROM_CLIENT: 'SEND_PLAYER_TIME_FROM_CLIENT',
    SEND_PLAYER_TIME_FROM_SERVER: 'SEND_PLAYER_TIME_FROM_SERVER',
    SEND_SCORES_FROM_SERVER: 'SEND_SCORES_FROM_SERVER',
    SEND_SCORES_FROM_CLIENT: 'SEND_SCORES_FROM_CLIENT',
}